[package]
name = "rs-blocks-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.77", features = ["full"] }

[lib]
proc-macro = true

[dev-dependencies]
regex = "1.11.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
