[Brightness]
path_to_current_brightness = "/sys/class/backlight/intel_backlight/brightness"
max_brightness = 120000

[Volume]

[Network]
path_to_rx = "/sys/class/net/wlan0/statistics/rx_bytes"
path_to_tx = "/sys/class/net/wlan0/statistics/tx_bytes"

[Memory]

[Cpu]
alpha = 0.05

[Battery]
path_to_status = "/sys/class/power_supply/BAT0/status"
path_to_charge_now = "/sys/class/power_supply/BAT0/energy_now"
path_to_charge_full = "/sys/class/power_supply/BAT0/energy_full"
alpha = 0.02

[Time]
